project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "The pmplots Gallery"
  subtitle: "Plots for Pharmacometrics"
  author: "Kyle Baron, Pharm.D., Ph.D."
  date: today
  date-format: medium
  repo-url: https://github.com/metrumresearchgroup/pmp-book
  repo-subdir: book
  repo-branch: main
  repo-actions: [source, issue]
  search: 
    location: navbar
    type: overlay
  chapters:
    - index.qmd
    - col-label.qmd
    - dv-pred.qmd
    - dv-pred-ipred.qmd
    - residuals.qmd
    - npde.qmd
    - eta.qmd
    - wrap.qmd
    - pairs.qmd
    - vectorized.qmd
    - data-summary.qmd
    - custom.qmd
  navbar: 
    background: white
    foreground: darkgrey
    right:
      - text: pmtables
        href: https://metrumresearchgroup.github.io/pmt-book
      - icon: book
        href: https://metrumresearchgroup.github.io/pmplots
      - icon: globe2
        href: https://metrumrg.com

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    fig-align: center
    fontsize: "15pt"
    linkcolor: "#00b4f1"
    title-block-banner: "#00b4f1"
    title-block-banner-color: "white"
