
```{r setup, include = FALSE}
source("global.R")
```

# NPDE plots

## Versus TIME `[npde_time]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_time(df)
```


## Versus TAD `[npde_tad]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_tad(df)
```


## Versus TAFD `[npde_tafd]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_tafd(df)
```

## Versus PRED `[npde_pred]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_pred(df)
```

## Versus continuous  `[npde_cont]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_cont(df, "WT")
```

### Vectorized

These plots can take in a vector of continuous column names
and return a list of plots which can be arranged. 

```{r}
#| fig-width: 7
#| fig-height: 6
covariates <- c("WT", "AGE", "ALB")

npde_cont(df, covariates) %>% 
  pm_grid()
```


## Versus categorical  `[npde_cat]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_cat(df, "STUDYc")
```

## QQ-plot  `[npde_q]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_q(df)
```


## Histogram `[npde_hist]`

```{r}
#| fig-width: 4
#| fig-height: 4
npde_hist(df)
```


